name: phyling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.81
  - clipkit>=2.0.1
  - matplotlib>=3.5.3
  - muscle>=5.1
  - pyhmmer>=0.8.1
  - python>=3.7.12
  - veryfasttree>=4.0.2
