name: phyling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aster>=1.19
  - biopython>=1.81
  - clipkit>=2.1.1
  - fasttree>=2.1.1
  - iqtree>=2.4.0,<3.0
  - matplotlib>=3.5.3
  - muscle>=5.3
  - numpy>=2.2.1
  - phykit>=2.0.1
  - pyfaidx>=0.8.1.3
  - pyhmmer>=0.11.0
  - python>=3.9
  - raxml-ng>=1.2.2
