name: phyling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.81
  - matplotlib>=3.5.3
  - muscle>=5.1
  - numpy
  - pyhmmer>=0.10.2
  - python>=3.7.12
  - veryfasttree>=4.0.2
