name: phyling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aster>=1.16
  - biopython>=1.81
  - clipkit>=2.1.1
  - fasttree>=2.1.11
  - iqtree>=2.2.6
  - matplotlib>=3.5.3
  - muscle>=5.1
  - numpy>=1.26.0
  - phykit>=1.19.4
  - pyfaidx>=0.8.1.3
  - pyhmmer>=0.10.4
  - python>=3.9
  - raxml-ng>=1.2.2
