name: Build raxml-ng

on: workflow_call

jobs:
  build_raxml:
    name: Build raxml-ng
    runs-on: ubuntu-latest

    steps:
      - name: Cache raxml-ng
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/raxml-ng
          key: ${{ runner.os }}-raxml-ng

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install build-essential g++ wget unzip

      - name: Download raxml-ng executable
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/amkozlov/raxml-ng/releases/download/1.2.2/raxml-ng_v1.2.2_linux_x86_64.zip
          unzip raxml-ng_v1.2.2_linux_x86_64.zip

      - name: Move executable
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p ~/.local/bin
          cp raxml-ng ~/.local/bin/
          chmod +x ~/.local/bin/raxml-ng

      - name: Export raxml-ng to PATH and verify
        run: |
          export PATH=$PATH:$HOME/.local/bin
          which raxml-ng
