name: Build IQTree

on: workflow_call

jobs:
  build_iqtree:
    name: Build IQTree
    runs-on: ubuntu-latest

    steps:
      - name: Cache IQTree
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/iqtree2
          key: ${{ runner.os }}-IQTree

      - name: Download IQTree executable
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install wget
          wget https://github.com/iqtree/iqtree2/releases/download/v2.4.0/iqtree-2.4.0-Linux-intel.tar.gz
          tar zxf iqtree-2.4.0-Linux-intel.tar.gz

      - name: Move executable
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p ~/.local/bin
          cp iqtree-2.4.0-Linux-intel/bin/iqtree2 ~/.local/bin/
          chmod +x ~/.local/bin/iqtree2

      - name: Export IQTree to PATH and verify
        run: |
          export PATH=$PATH:$HOME/.local/bin
          which iqtree2
