name: CI/Conda build and test

on:
  push:
    branches: ["main", "dev"]
    paths: ["**.py", "environment.yml"]
  pull_request:
    branches: ["main", "dev"]
    paths: ["**.py", "environment.yml"]
  workflow_dispatch:
  workflow_call:

jobs:
  conda-build-and-test:
    name: Conda build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - run: git fetch --tags

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          create-args: >-
            python=3.10
            flake8
            pytest
            pytest-cov

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=130 --statistics --ignore=E203,W503,E402
        shell: micromamba-shell {0}

      - name: Install package
        run: pip install .
        shell: micromamba-shell {0}

      - name: Pytest
        run: pytest --runslow -vv
        shell: micromamba-shell {0}
