name: Conda build

on:
  push:
    branches: ["main", "dev"]
    paths: ["**.py", "environment.yml"]
  pull_request:
    branches: ["main", "dev"]
    paths: ["**.py", "environment.yml"]
  workflow_dispatch:

jobs:
  build_ASTER:
    runs-on: ubuntu-latest

    steps:
      - name: Cache ASTER binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/astral
          key: ASTER-Linux

      - name: Install dependencies
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then sudo apt-get install build-essential cmake g++ wget unzip; \
          fi

      - name: Build ASTER
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then \
            wget https://github.com/chaoszhang/ASTER/archive/refs/heads/Linux.zip; \
            unzip Linux.zip; \
            cd ASTER-Linux; \
            make; \
          fi

      - name: Move Binary
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then \
            mkdir -p ~/.local/bin; \
            cp ASTER-Linux/bin/astral ~/.local/bin/; \
            chmod +x ~/.local/bin/astral; \
          fi
        working-directory: ${{ github.workspace }}

      - name: Export ASTER to PATH and verify
        run: |
          export PATH=$PATH:$HOME/.local/bin
          which astral

  build-conda:
    runs-on: ubuntu-latest

    needs: build_ASTER

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=3.10
            flake8
            pytest

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics
        shell: micromamba-shell {0}

      - name: Install package
        run: |
          pip install .
        shell: micromamba-shell {0}

      - name: Cache ASTER binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/astral
          key: ASTER-Linux

      - name: Test with pytest
        run: |
          pytest
        shell: micromamba-shell {0}
