name: Python versions

on:
  push:
    branches: ["main", "dev"]
    paths: ["**.py", "requirements.txt"]
  pull_request:
    branches: ["main", "dev"]
    paths: ["**.py", "requirements.txt"]
  workflow_dispatch:

jobs:
  build_ASTER:
    runs-on: ubuntu-latest

    steps:
      - name: Cache VeryFastTree binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/astral
          key: ASTER-Linux

      - name: Install dependencies
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then sudo apt-get install build-essential cmake g++ wget unzip; \
          fi

      - name: Build ASTER
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then \
            wget https://github.com/chaoszhang/ASTER/archive/refs/heads/Linux.zip; \
            unzip Linux.zip; \
            cd ASTER-Linux; \
            make; \
          fi

      - name: Move Binary
        run: |
          if ! [ -f ~/.local/bin/astral ]; \
            then \
            mkdir -p ~/.local/bin; \
            cp ASTER-Linux/bin/astral ~/.local/bin/; \
            chmod +x ~/.local/bin/astral; \
          fi
        working-directory: ${{ github.workspace }}

      - name: Export ASTER to PATH and verify
        run: |
          export PATH=$PATH:$HOME/.local/bin
          which astral

  build_VeryFastTree:
    runs-on: ubuntu-latest

    steps:
      - name: Cache ASTER binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/VeryFastTree
          key: VeryFastTree-Linux

      - name: Install dependencies
        run: |
          if ! [ -f ~/.local/bin/VeryFastTree ]; \
            then sudo apt-get install build-essential cmake g++ wget unzip; \
          fi

      - name: Build VeryFastTree
        run: |
          if ! [ -f ~/.local/bin/VeryFastTree ]; \
            then \
            wget https://github.com/citiususc/veryfasttree/archive/refs/tags/v4.0.3.zip; \
            unzip v4.0.3.zip; \
            cd veryfasttree-4.0.3; \
            cmake .; \
            make; \
          fi

      - name: Move Binary
        run: |
          if ! [ -f ~/.local/bin/VeryFastTree ]; \
            then \
            mkdir -p ~/.local/bin; \
            cp veryfasttree-4.0.3/VeryFastTree ~/.local/bin/; \
            chmod +x ~/.local/bin/VeryFastTree; \
          fi
        working-directory: ${{ github.workspace }}

      - name: Export VeryFastTree to PATH and verify
        run: |
          export PATH=$PATH:$HOME/.local/bin
          which VeryFastTree

  build:
    runs-on: ubuntu-latest

    needs: [build_ASTER, build_VeryFastTree]

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics

      - name: Install package
        run: |
          pip install .

      - name: Cache ASTER binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/astral
          key: ASTER-Linux

      - name: Cache VeryFastTree binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/VeryFastTree
          key: VeryFastTree-Linux

      - name: Test with pytest
        run: |
          pytest
